app.constant('USERDATA', [
{
	"id": 0,
	"first_name": "Test",
	"last_name": "Test",
	"email": "test@test.com",
	"gender": "Male",
	"username": "test",
	"password": "test"
},{
	"id": 1,
	"first_name": "Callean",
	"last_name": "Berriball",
	"email": "cberriball0@japanpost.jp",
	"gender": "Male",
	"username": "cberriball0",
	"password": "9qcM8d9X"
}, {
	"id": 2,
	"first_name": "Allis",
	"last_name": "Greatbach",
	"email": "agreatbach1@bloomberg.com",
	"gender": "Female",
	"username": "agreatbach1",
	"password": "1hBLO2"
}, {
	"id": 3,
	"first_name": "Gianna",
	"last_name": "Nerne",
	"email": "gnerne2@canalblog.com",
	"gender": "Female",
	"username": "gnerne2",
	"password": "VlxjYRyAdBo"
}, {
	"id": 4,
	"first_name": "Des",
	"last_name": "Reid",
	"email": "dreid3@soup.io",
	"gender": "Male",
	"username": "dreid3",
	"password": "wPtuq3imx"
}, {
	"id": 5,
	"first_name": "Micah",
	"last_name": "Korf",
	"email": "mkorf4@google.com.br",
	"gender": "Male",
	"username": "mkorf4",
	"password": "UUOnBnOTcRJP"
}, {
	"id": 6,
	"first_name": "Gerick",
	"last_name": "Irvine",
	"email": "girvine5@nature.com",
	"gender": "Male",
	"username": "girvine5",
	"password": "JClSCF1"
}, {
	"id": 7,
	"first_name": "Cyb",
	"last_name": "Daintier",
	"email": "cdaintier6@4shared.com",
	"gender": "Female",
	"username": "cdaintier6",
	"password": "KkivgeIYPI"
}, {
	"id": 8,
	"first_name": "Ase",
	"last_name": "Bohills",
	"email": "abohills7@businessinsider.com",
	"gender": "Male",
	"username": "abohills7",
	"password": "YPMkJYVWBEX"
}, {
	"id": 9,
	"first_name": "Corly",
	"last_name": "Terrans",
	"email": "cterrans8@163.com",
	"gender": "Female",
	"username": "cterrans8",
	"password": "uv3rCjMp"
}, {
	"id": 10,
	"first_name": "Daniela",
	"last_name": "Pieche",
	"email": "dpieche9@fotki.com",
	"gender": "Female",
	"username": "dpieche9",
	"password": "81ooVwDAbOyn"
}]);